// File generated by hand from the Firebase console web config.
// Web is fully configured. iOS/Android can be added later by registering
// those apps in the Firebase console and pasting their config here.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
      case TargetPlatform.android:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'This platform is not configured yet. Register the app in the '
          'Firebase console (project yatty-cf0d5) and add its FirebaseOptions '
          'here. Web is currently the only supported target.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj-w4sYp8h7zwGySsZbXtuYKkbVeHRUJk',
    authDomain: 'yatty-cf0d5.firebaseapp.com',
    projectId: 'yatty-cf0d5',
    storageBucket: 'yatty-cf0d5.firebasestorage.app',
    messagingSenderId: '277290360096',
    appId: '1:277290360096:web:f8cb0118727fd1750f4b45',
    measurementId: 'G-PBKN1PW5XM',
  );
}
